language: node_js
node_js:
  - 8

deploy:
  local-dir: build
  skip-cleanup: true
  targe-branch: gh-pages
  github-token: $GITHUB_TOKEN
  on:
    branch: develop

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
